import Navbar from "@/components/Navbar";
import "./globals.css";
import HeroSection from "@/components/HeroSection";
import JoinSection from "@/components/JoinSection";
import JobSection from "@/components/JobSection";
import FeatureSection from "@/components/FeatureSection";
import AwardsSection from "@/components/AwardsSection";
import ContactSection from "@/components/ContactSection";
import FAQSection from "@/components/FAQSection";
import OurFacilitySection from "@/components/OurFacilitySection";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import ApplyNowSection from "@/components/ApplyNowSection";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <HeroSection />
        <JoinSection />
        <JobSection />
        <FeatureSection />
        <AwardsSection />
        <ContactSection />
        <FAQSection />
        <OurFacilitySection />
        <ApplyNowSection />
        <Footer />
        {/* {children} */}
      </body>
    </html>
  );
}


